# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_create_model_opinion_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(default=None, max_length=255)),
                ('response', models.TextField()),
                ('opinion_poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.OpinionPoll')),
            ],
            options={
                'db_table': 'polls_responses',
            },
        ),
    ]
